version: "3.9"

services:
  db:
    image: mysql:8.0.22
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: squaaat
    ports:
      - 3306:3306
