paths:
  /foobar:
    post:
      operationId: idOfFoobarEndpoint
      responses:
        "200":
          $ref: '#/responses/foobarResponse'
      summary: Foobar does some amazing stuff.
      tags:
      - foobar-tag
swagger: "2.0"
